"""empty message

Revision ID: 278489e43ede
Revises: 6cdc51473492
Create Date: 2022-08-11 23:22:41.626905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278489e43ede'
down_revision = '6cdc51473492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
